-- MySQL Script generated by MySQL Workbench
-- Tue Nov 21 11:46:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE,g4bg4b SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema g4b
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `g4b` ;

-- -----------------------------------------------------
-- Schema g4b
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `g4b` DEFAULT CHARACTER SET utf8 ;
USE `g4b` ;

-- -----------------------------------------------------
-- Table `g4b`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `g4b`.`client` ;

CREATE TABLE IF NOT EXISTS `g4b`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `nbTel` INT NOT NULL,
  `adress` VARCHAR(120) NOT NULL,
  `reservation_id` INT NOT NULL,
  `facture_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_reservation_idx` (`reservation_id` ASC) VISIBLE,
  INDEX `fk_client_facture1_idx` (`facture_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_reservation`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `g4b`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_facture1`
    FOREIGN KEY (`facture_id`)
    REFERENCES `g4b`.`facture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g4b`.`facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `g4b`.`facture` ;

CREATE TABLE IF NOT EXISTS `g4b`.`facture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nbFacture` DOUBLE NOT NULL,
  `client` VARCHAR(65) NOT NULL,
  `delayService` VARCHAR(45) NOT NULL,
  `costTot` DECIMAL NOT NULL,
  `reservation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_facture_reservation1_idx` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `fk_facture_reservation1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `g4b`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g4b`.`personnel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `g4b`.`personnel` ;

CREATE TABLE IF NOT EXISTS `g4b`.`personnel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `poste` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g4b`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `g4b`.`reservation` ;

CREATE TABLE IF NOT EXISTS `g4b`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nbReservation` INT NOT NULL,
  `client` VARCHAR(65) NOT NULL,
  `dateStartEnd` DATE NOT NULL,
  `roomBook` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g4b`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `g4b`.`room` ;

CREATE TABLE IF NOT EXISTS `g4b`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nbRoom` DOUBLE NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `disponibility` VARCHAR(100) NOT NULL,
  `tarif` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g4b`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `g4b`.`service` ;

CREATE TABLE IF NOT EXISTS `g4b`.`service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nameService` VARCHAR(100) NOT NULL,
  `cost` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
